<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[openBrowser]]>
    </line>
    <line>
      <![CDATA[login]]>
    </line>
    <line>
      <![CDATA[logout]]>
    </line>
    <line>
      <![CDATA[login]]>
    </line>
    <line>
      <![CDATA[modifyCustomer]]>
    </line>
    <line>
      <![CDATA[modifyCustomer has got passed]]>
    </line>
    <line>
      <![CDATA[logout]]>
    </line>
    <line>
      <![CDATA[deleteCustomer has got skipped]]>
    </line>
    <line>
      <![CDATA[closeBrowser]]>
    </line>
  </reporter-output>
  <suite started-at="2023-10-05T12:22:56 IST" name="Default suite" finished-at="2023-10-05T12:23:14 IST" duration-ms="18369">
    <groups>
    </groups>
    <test started-at="2023-10-05T12:22:56 IST" name="Default test" finished-at="2023-10-05T12:23:14 IST" duration-ms="18369">
      <class name="com.actitime.testscript.Customer_Module">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:com.actitime.testscript.Customer_Module@179ece50]" started-at="2023-10-05T12:22:56 IST" name="openBrowser" finished-at="2023-10-05T12:23:05 IST" duration-ms="9335" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[openBrowser]]>
            </line>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:com.actitime.testscript.Customer_Module@179ece50]" started-at="2023-10-05T12:23:05 IST" name="login" finished-at="2023-10-05T12:23:05 IST" duration-ms="132" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[login]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="createCustomer()[pri:0, instance:com.actitime.testscript.Customer_Module@179ece50]" started-at="2023-10-05T12:23:05 IST" name="createCustomer" finished-at="2023-10-05T12:23:05 IST" duration-ms="10" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.actitime.testscript.Customer_Module.createCustomer(Customer_Module.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCustomer -->
        <test-method is-config="true" signature="logout()[pri:0, instance:com.actitime.testscript.Customer_Module@179ece50]" started-at="2023-10-05T12:23:09 IST" name="logout" finished-at="2023-10-05T12:23:10 IST" duration-ms="1305" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[logout]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="login()[pri:0, instance:com.actitime.testscript.Customer_Module@179ece50]" started-at="2023-10-05T12:23:10 IST" name="login" finished-at="2023-10-05T12:23:10 IST" duration-ms="88" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[login]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="modifyCustomer()[pri:0, instance:com.actitime.testscript.Customer_Module@179ece50]" started-at="2023-10-05T12:23:10 IST" name="modifyCustomer" finished-at="2023-10-05T12:23:10 IST" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[modifyCustomer]]>
            </line>
            <line>
              <![CDATA[modifyCustomer has got passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- modifyCustomer -->
        <test-method is-config="true" signature="logout()[pri:0, instance:com.actitime.testscript.Customer_Module@179ece50]" started-at="2023-10-05T12:23:10 IST" name="logout" finished-at="2023-10-05T12:23:14 IST" duration-ms="3932" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[logout]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method signature="deleteCustomer()[pri:0, instance:com.actitime.testscript.Customer_Module@179ece50]" started-at="2023-10-05T12:23:14 IST" name="deleteCustomer" finished-at="2023-10-05T12:23:14 IST" depends-on-methods="com.actitime.testscript.Customer_Module.createCustomer" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.actitime.testscript.Customer_Module.deleteCustomer() on instance com.actitime.testscript.Customer_Module@179ece50 depends on not successfully finished methods 
[com.actitime.testscript.Customer_Module.createCustomer() on instance com.actitime.testscript.Customer_Module@179ece50]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.actitime.testscript.Customer_Module.deleteCustomer() on instance com.actitime.testscript.Customer_Module@179ece50 depends on not successfully finished methods 
[com.actitime.testscript.Customer_Module.createCustomer() on instance com.actitime.testscript.Customer_Module@179ece50]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[deleteCustomer has got skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.actitime.testscript.Customer_Module@179ece50]" started-at="2023-10-05T12:23:14 IST" name="closeBrowser" finished-at="2023-10-05T12:23:14 IST" duration-ms="128" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[closeBrowser]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.actitime.testscript.Customer_Module -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
